### ISSUE TITLE
Integration with other crates

### ISSUE THREAD

**Issue by bjadamson** [jDomantas/internal-iterator#1]
Hello there!

I saw your post of reddit today, congratulations on your release 🥳 🎈. I was wondering if you were interested in trying to integrate this with other crates in the community. The [slab-tree](https://github.com/iwburns/slab-tree) crate seems like a perfect use-case for a crate like this. While I don't own it, I do see the obvious potential between these two crates to create easily std-like iterable trees. Do you think a tree like API like slab-tree would be a good candidate for your crate to integrate with?

Thanks!

**Comment by jDomantas** [comment]
Slab-tree in particular does not need it - [they already have iterators](https://docs.rs/slab_tree/0.3.2/slab_tree/struct.NodeRef.html#method.traverse_pre_order) over the tree, and if you wanted to use them together with this crate you can just sprinkle some `.into_internal()` calls. Although `InternalIterator` implementations would be simpler, it won't be worth it to provide both, and it definitely would not be good for them to replace current iterators.

In general I think that any "serious" crate should aim to provide `Iterator` implementations for traversals because it would yield a better integration with the rest of the ecosystem. Given a large enough number of users the benefit of better api outweighs the increase in complexity on the crate implementation side. Of course a crate's author is still free to chose to use this instead of `Iterator` if they need it or want reduced complexity.

I think the ideal use case that would be reasonably common is non-library crates. There no one aside from the author cares about the api, so the implementation complexity is more relevant compared to api usefulness. But of course then using this would be entirely up to the author(s).
