### ISSUE TITLE
Question: How to implement a mutable iterator?

### ISSUE THREAD

**Issue by LennysLounge** [jDomantas/internal-iterator#19]
I need to iterate over all items in a composite tree and wanted to use this crate for that.
However the example in the readme only shows where the iterated item is an owned type. I would like to have an iterator over `&T` and `&mut T` types.

The immutable case is simply enough but for the mutable iterator i am struggeling with the borrow checker.
This was my attempt:
```rust
use std::ops::ControlFlow;

use internal_iterator::InternalIterator;

struct Node {
    nodes: Vec<Node>,
}
struct NodeIteratorMut<'a> {
    n: &'a mut Node,
}
impl<'a> InternalIterator for NodeIteratorMut<'a> {
    type Item = &'a mut Node;

    fn try_for_each<R, F>(self, mut f: F) -> std::ops::ControlFlow<R>
    where
        F: FnMut(Self::Item) -> std::ops::ControlFlow<R>,
    {
        iter_node(self.n, &mut f)
    }
}
fn iter_node<'a, T>(
    node: &'a mut Node,
    f: &mut impl FnMut(&'a mut Node) -> ControlFlow<T>,
) -> ControlFlow<T> {
    f(node)?;
    node.nodes.iter_mut().try_for_each(|n| iter_node(n, f))
}

fn main() {}
```
Which does not work :
```
error[E0499]: cannot borrow `node.nodes` as mutable more than once at a time
  --> crates\tree_view\examples\iter_test.rs:26:5
   |
21 | fn iter_node<'a, T>(
   |              -- lifetime `'a` defined here
...
25 |     f(node)?;
   |     -------
   |     | |
   |     | first mutable borrow occurs here
   |     argument requires that `*node` is borrowed for `'a`
26 |     node.nodes.iter_mut().try_for_each(|n| iter_node(n, f))
   |     ^^^^^^^^^^^^^^^^^^^^^ second mutable borrow occurs here
```

How could this be implemented?

**Comment by jDomantas** [comment]
The code that you provided cannot work because it tries to yield aliasing mutable references (by yielding references to parent and children nodes, even though you can access children through parents). Here's an example how that is a problem:

```rust
fn main() {
    // we have two nodes, one is a child of the other:
    let mut node = Node {
        nodes: vec![Node { nodes: Vec::new() }],
    };
    let all = NodeIteratorMut { n: &mut node }.collect::<Vec<_>>();
    // now all[0] is a &mut reference to the root, all[1] is a &mut reference to the child
    all[0].nodes.clear();
    // uh oh, all[1] is dangling because that node is stored in the vector we just cleared
    println!("child node: {:?}", all[1]);
}
```

I see two options:

1. If it is sufficient for the iterator to return information about the node but not about its children, then it will work if you avoid yielding references to children vectors. This is a simpler option, but it will not be usable if you do need the children. Example:

    ```rust
    use std::ops::ControlFlow;

    use internal_iterator::InternalIterator;

    struct NodeData { ... }
    struct Node {
        data: NodeData,
        nodes: Vec<Node>,
    }
    struct NodeIteratorMut<'a> {
        n: &'a mut Node,
    }
    impl<'a> InternalIterator for NodeIteratorMut<'a> {
        type Item = &'a mut NodeData; // changed here, we no longer return node's children

        fn try_for_each<R, F>(self, mut f: F) -> std::ops::ControlFlow<R>
        where
            F: FnMut(Self::Item) -> std::ops::ControlFlow<R>,
        {
            iter_node(self.n, &mut f)
        }
    }
    fn iter_node<'a, T>(
        node: &'a mut Node,
        f: &mut impl FnMut(&'a mut NodeData) -> ControlFlow<T>,
    ) -> ControlFlow<T> {
        f(&mut node.data)?;
        node.nodes.iter_mut().try_for_each(|n| iter_node(n, f))
    }
    ```

2. Use a streaming iterator instead (e.g. something like [`streaming_iterator` crate](https://docs.rs/streaming-iterator/latest/streaming_iterator/index.html)). However, that crate is for external iterators, so implementing an iterator for a tree structure will be quite difficult. In theory there could be a crate for streaming-internal-iterators (so you would get both capabilities of streaming, and ease of implementation of internal iteration), but sadly I don't know any.

**Comment by LennysLounge** [comment]
Thank you, that was honestly the answer i was expecting. Your example on why this could never works makes a lot of sense to me.
